### PR TITLE
Added clean as dependancy to make safe

### PR DESCRIPTION
**Pull request by marcusnaslund**
As a copy of the change performed in https://github.com/magic-lang/rock/pull/43

@shamanas

### CODE REVIEW

**Comment by shamanas** [comment]
Thanks, merging :)

**Comment by marcusnaslund** [comment]
Better make safe than make sorry. :)

**Comment by fasterthanlime** [comment]
we can add reactions on github now? what is this sorcery

**Comment by shamanas** [comment]
Yeah I just noticed it too :)

**Comment by marcusnaslund** [comment]
Wow, my first "likes" on Github. Thanks, people.

**Comment by kirbyfan64** [comment]
Wow, does [no one here view /r/programming](https://www.reddit.com/r/programming/comments/49vqzv/github_adds_reactions_to_pull_requests_issues_and/)?

**Comment by vendethiel** [comment]
Some of us spend so much time on github, we see it before it's on reddit :P

**Pull request merged**
